### ISSUE TITLE
can i ask for your degree?

### ISSUE THREAD

**Issue by zhangzibao** [bamtercelboo/pytorch_word2vec#6]
I'm  desperate  for the nlp , there are too many models and math that I can not  understand soon.
I'm stupid! now it's 3 o'clock,how can I do,I'm pain.

**Comment by dalinvip** [comment]
Hi, it's always painful at first, patience and persistence will give you hope, come on.
You can do some basic NLP tasks, like sentiment classification. add some nlp groups, qq or wechat,  more communication with others.

Best wishes.

**Comment by zhangzibao** [comment]
> Hi, it's always painful at first, patience and persistence will give you hope, come on.
> You can do some basic NLP tasks, like sentiment classification. add some nlp groups, qq or wechat, more communication with others.
> 
> Best wishes.

**Comment by zhangzibao** [comment]
thank you

> Hi, it's always painful at first, patience and persistence will give you hope, come on.
> You can do some basic NLP tasks, like sentiment classification. add some nlp groups, qq or wechat, more communication with others.
> 
> Best wishes.

**Comment by zhangzibao** [comment]
> Hi, it's always painful at first, patience and persistence will give you hope, come on.
> You can do some basic NLP tasks, like sentiment classification. add some nlp groups, qq or wechat, more communication with others.
> 
> Best wishes.

Thank you very much ， I'm  touched deeply.
I will be more brave to overcome the hardship！
